### PR TITLE
Fix issues and improve code quality

### LINKED ISSUE #13: Change About me section
- [x] Make the about me section the same as LinkedIn about me section

### PR DESCRIPTION
**Pull request by descholar-ceo**
### What does this PR do?
It fixes [#13 ](https://github.com/descholar-ceo/portfolio/issues/13) 
### Tasks
- [x] Remove unnecessary commented codes
- [x] Change the about me section

### CODE REVIEW

**Comment by descholar-ceo** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 19
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379&bid=19777225)

File: src/components/HomePage.js [hunk 1]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
+                    Being a technology enthusiast, I decided to dive deep in programming and developed an android application 
+                    that helps me keep track of my phone logs and SMS which encouraged me that programming is feasible. So I 
+                    joined the Andela stack up to master all of the needed technical and soft skills that professional software 
+                    engineers use in their daily life, and after that, I attended Microverse, an online coding school.
                   </p>
-
                   <p>
-                    Either of them you choose to be, go ahead and get in touch with me!
+                    Now, I can comfortably build solutions based on ideas, help engineering teams to escalate their productivity 
+                    by delivering the product before or on deadlines, help new businesses to grow their productivity by automating
```
Comment (descholar-ceo) [inline src/components/HomePage.js:138]: Codacy found an issue: [This line has a length of 131. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

Comment (descholar-ceo) [inline src/components/HomePage.js:138]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 2]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
-                  </p>
-
-                  <p>
-                    I graduated from University of Rwanda in College of Medicine
-                    and Health sciences in 2014, and in 2016 I went to Kigali independent
-                    University to study computer sciences, when I grabbed the basics of programming
-                    I dropped out before graduating because I wanted to focus muore on software
-                    engineering in a professiona way. Now I am ready to bring solutions using
-                    programming.
+                   I am a full-stack software engineer with expertise in NodeJS, PostgreSQL, React, Ruby, Ruby on Rails,
```
Comment (descholar-ceo) [inline src/components/HomePage.js:119]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 3]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
-                    Hard-working, focused, innovative, result-oriented, and growth mindset are
-                    the top four adjectives that best define my aptitude towards work.
+                    I am currently open to full-stack development posts, for global products, startups, and many more.
                   </p>
-
                   <p>
-                    Co-workers see me as a team player who gives his best in sharing ideas,
-                    as well as creating and designing innovative experiences.
+                    Since I started my professional journey in 2014 as a health care provider, I realized that programming 
+                    had the potential to change our world through solving the most challenging, tiresome, and repetitive
```
Comment (descholar-ceo) [inline src/components/HomePage.js:127]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 4]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
                   <p>
-                    Hard-working, focused, innovative, result-oriented, and growth mindset are
-                    the top four adjectives that best define my aptitude towards work.
+                    I am currently open to full-stack development posts, for global products, startups, and many more.
                   </p>
-
                   <p>
-                    Co-workers see me as a team player who gives his best in sharing ideas,
-                    as well as creating and designing innovative experiences.
+                    Since I started my professional journey in 2014 as a health care provider, I realized that programming
```
Comment (descholar-ceo) [inline src/components/HomePage.js:126]: Codacy found an issue: [This line has a length of 123. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 5]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
-
-                  <p>
-                    I graduated from University of Rwanda in College of Medicine
-                    and Health sciences in 2014, and in 2016 I went to Kigali independent
-                    University to study computer sciences, when I grabbed the basics of programming
-                    I dropped out before graduating because I wanted to focus muore on software
-                    engineering in a professiona way. Now I am ready to bring solutions using
-                    programming.
+                   I am a full-stack software engineer with expertise in NodeJS, PostgreSQL, React, Ruby, Ruby on Rails, 
+                   Semantic HTML5, CSS3, Git, Agile methodology, Mobile applications, Technical Team Lead, and mentor.
```
Comment (descholar-ceo) [inline src/components/HomePage.js:120]: Codacy found an issue: [This line has a length of 118. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 6]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
+                    had the potential to change our world through solving the most challenging, tiresome, and repetitive 
+                    work we do manually.
                   </p>
-
                   <p>
-                    Friends and family members see me as a nerd person, who invest most of his
-                    time for inventing new technology, and who will once move the world to the
-                    extend of changing people lifestyle.
+                    Being a technology enthusiast, I decided to dive deep in programming and developed an android application 
+                    that helps me keep track of my phone logs and SMS which encouraged me that programming is feasible. So I
```
Comment (descholar-ceo) [inline src/components/HomePage.js:132]: Codacy found an issue: [This line has a length of 125. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js (hunk 2 above)
Comment (descholar-ceo) [inline src/components/HomePage.js:119]: Codacy found an issue: [This line has a length of 121. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 7]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
+                    Since I started my professional journey in 2014 as a health care provider, I realized that programming 
+                    had the potential to change our world through solving the most challenging, tiresome, and repetitive 
+                    work we do manually.
                   </p>
-
                   <p>
-                    Friends and family members see me as a nerd person, who invest most of his
-                    time for inventing new technology, and who will once move the world to the
-                    extend of changing people lifestyle.
+                    Being a technology enthusiast, I decided to dive deep in programming and developed an android application
```
Comment (descholar-ceo) [inline src/components/HomePage.js:131]: Codacy found an issue: [This line has a length of 126. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 8]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
-                    extend of changing people lifestyle.
+                    Being a technology enthusiast, I decided to dive deep in programming and developed an android application 
+                    that helps me keep track of my phone logs and SMS which encouraged me that programming is feasible. So I 
+                    joined the Andela stack up to master all of the needed technical and soft skills that professional software 
+                    engineers use in their daily life, and after that, I attended Microverse, an online coding school.
                   </p>
-
                   <p>
-                    Either of them you choose to be, go ahead and get in touch with me!
+                    Now, I can comfortably build solutions based on ideas, help engineering teams to escalate their productivity
```
Comment (descholar-ceo) [inline src/components/HomePage.js:137]: Codacy found an issue: [This line has a length of 129. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

Comment (descholar-ceo) [inline src/components/HomePage.js:137]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 9]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
                   </p>
-
                   <p>
-                    Friends and family members see me as a nerd person, who invest most of his
-                    time for inventing new technology, and who will once move the world to the
-                    extend of changing people lifestyle.
+                    Being a technology enthusiast, I decided to dive deep in programming and developed an android application 
+                    that helps me keep track of my phone logs and SMS which encouraged me that programming is feasible. So I 
+                    joined the Andela stack up to master all of the needed technical and soft skills that professional software 
+                    engineers use in their daily life, and after that, I attended Microverse, an online coding school.
```
Comment (descholar-ceo) [inline src/components/HomePage.js:134]: Codacy found an issue: [This line has a length of 118. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js (hunk 4 above)
Comment (descholar-ceo) [inline src/components/HomePage.js:126]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js (hunk 6 above)
Comment (descholar-ceo) [inline src/components/HomePage.js:132]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js (hunk 7 above)
Comment (descholar-ceo) [inline src/components/HomePage.js:131]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 10]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
-                    engineering in a professiona way. Now I am ready to bring solutions using
-                    programming.
+                   I am a full-stack software engineer with expertise in NodeJS, PostgreSQL, React, Ruby, Ruby on Rails, 
+                   Semantic HTML5, CSS3, Git, Agile methodology, Mobile applications, Technical Team Lead, and mentor.
                   </p>
-
                   <p>
-                    Hard-working, focused, innovative, result-oriented, and growth mindset are
-                    the top four adjectives that best define my aptitude towards work.
+                    I am currently open to full-stack development posts, for global products, startups, and many more.
```
Comment (descholar-ceo) [inline src/components/HomePage.js:123]: Codacy found an issue: [This line has a length of 118. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js [hunk 11]
```diff
@@ -135,49 +116,27 @@ class HomePage extends Component {
...
+                    work we do manually.
                   </p>
-
                   <p>
-                    Friends and family members see me as a nerd person, who invest most of his
-                    time for inventing new technology, and who will once move the world to the
-                    extend of changing people lifestyle.
+                    Being a technology enthusiast, I decided to dive deep in programming and developed an android application 
+                    that helps me keep track of my phone logs and SMS which encouraged me that programming is feasible. So I 
+                    joined the Andela stack up to master all of the needed technical and soft skills that professional software
```
Comment (descholar-ceo) [inline src/components/HomePage.js:133]: Codacy found an issue: [Trailing spaces not allowed.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js (hunk 3 above)
Comment (descholar-ceo) [inline src/components/HomePage.js:127]: Codacy found an issue: [This line has a length of 121. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)

File: src/components/HomePage.js (hunk 11 above)
Comment (descholar-ceo) [inline src/components/HomePage.js:133]: Codacy found an issue: [This line has a length of 128. Maximum allowed is 100.](https://app.codacy.com/manual/descholar-ceo/portfolio/pullRequest?prid=6035379)
